Neos:
  Neos:
    modules:
      management:
        submodules:
          workspaces:
            controller: Shel\Neos\WorkspaceModule\Controller\WorkspacesController
            additionalResources:
              javaScripts:
                Shel.Neos.WorkspaceModule: 'resource://Shel.Neos.WorkspaceModule/Public/Assets/main.js'

    userInterface:
      translation:
        autoInclude:
          Shel.Neos.WorkspaceModule:
            - 'Main'
